# Dependabot Configuration for .NET Project

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependabot package update"
    open-pull-requests-limit: 5
